-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(IFNULL(P.PRICE,0) * IFNULL(O.SALES_AMOUNT,0)) "SALES"
FROM PRODUCT P LEFT JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SUM(IFNULL(P.PRICE,0) * IFNULL(O.SALES_AMOUNT,0)) DESC, P.PRODUCT_CODE ASC