-- 코드를 입력하세요
SELECT DISTINCT(R.CAR_ID) 
FROM CAR_RENTAL_COMPANY_CAR R JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON R.CAR_ID = RH.CAR_ID
WHERE R.CAR_TYPE LIKE "세단" AND SUBSTR(RH.START_DATE,6,2) = "10"
ORDER BY R.CAR_ID DESC